{% set name = "knock-knock" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/0d/06/b5006ab4afc432fca2bd1688c2c8257dd6efb8368f5a9d4675565f3e3032/knock_knock-{{ version }}.tar.gz"
  sha256: "69128026055c1b8aa7e7b6e2947f108b21795a406687199e1689bd9815197d5f"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - bokeh >=2.4.2
    - biopython >=1.80
    - h5py >=3.1.0
    - ipywidgets >=7.1.2
    - matplotlib-base >=2.1.2
    - nbformat >=4.4.0
    - numpy >=1.14.2
    - pandas >=0.22.0
    - pillow >=5.0.0
    - pysam >=0.14
    - pyyaml >=3.12
    - hits >=0.4.0
    - tqdm >=4.31.1    
    - blast ==2.7.1
    - minimap2 ==2.16
    - samtools >=1.9
    - star >=2.7.1
    - parallel >=20190522

test:
  imports:
    - knock_knock
  commands:
    - knock-knock -h
    - blastn -version
    - minimap2 --version
    - samtools --version
    - STAR --version

about:
  home: "https://github.com/jeffhussmann/knock-knock"
  license: "GPL-3"
  summary: "toolkit for analyzing CRISPR knock-in experiments"

extra:
  recipe-maintainers:
    - jeffhussmann
