{% set name = "fiji-omero_ij" %}
{% set version = "5.8.2" %}
 
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ome/omero-insight/releases/download/v{{ version }}/omero_ij-{{ version }}-all.jar
  sha256: 87ff6a57344e4503dbe1b3435a4b1418e35423df5c9e9e155246b4ebfbcc0ec3

build:
  number: 0
  noarch: generic

requirements:
  run:
    - fiji >=20220414

test:
  files:
    - test.groovy

about:
  home: https://github.com/ome/omero-insight
  license: GPLv2
  license_file: LICENSE.txt
  summary: ImageJ / Fiji plugin to visualize and manipulate both image data and metadata maintained at an OMERO server site.
  description: |
    The OMERO.insight Project is a sub-project of the Open Microscopy Environment Project, OME that focuses on delivering a client for the visualization and manipulation of both image data and metadata maintained at an OMERO server site.
  dev_url: https://github.com/ome/omero-insight
