{% set name = "fiji-simple_omero_client" %}
{% set version = "5.14.1" %}
 
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GReD-Clermont/simple-omero-client/releases/download/{{ version }}/simple-omero-client-{{ version }}.jar
  sha256: 5956fd9ea1002ee2a70f89b6fbfbea228d25f90b5a899e2888a972e7eb5a5ce7

build:
  number: 0
  noarch: generic

requirements:
  run:
    - fiji >=20220414
    - fiji-omero_ij <6.0.0

test:
  files:
    - test.groovy

about:
  home: https://github.com/GReD-Clermont/simple-omero-client
  license: GPLv2
  license_file: LICENSE.txt
  summary: Java library to simplify API to put/get objects on an OMERO server from Fiji/ImageJ.
  description: |
    This library presents a simplified API to put/get objects on an OMERO server.
  dev_url: https://github.com/GReD-Clermont/simple-omero-client
