{% set version="6.5.1" %}
{% set sha="e46e0fe60e6959f3867280b8759fc7a2b4cdb71d46675d487f090d08e2bdb8ad" %}

package:
  name: ena-webin-cli
  version: {{ version }}

build:
  noarch: generic
  number: 0

source:
    url: https://github.com/enasequence/webin-cli/releases/download/{{ version }}/webin-cli-{{ version }}.jar
    sha256: {{ sha }}

requirements:
  run:
    - openjdk >=8,<9
    - python

test:
  commands:
    - ena-webin-cli -version

about:
  home: https://github.com/enasequence/webin-cli
  license: Apache-2.0
  summary: Data submissions to ENA can be made using the Webin command line submission interface (Webin-CLI).
