{% set name = "cytoscape" %}
{% set version = "3.10.0" %}
{% set sha256 = "3273a9fdb67c4e1e5c5b77d2bfc2dd80904400635a02e7ba31614146da63355c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cytoscape/cytoscape/releases/download/{{ version }}/Cytoscape_{{ version|replace(".","_") }}_unix.sh
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - gettext
  host:
    - openjdk >=11,<=12
    - fontconfig
    - freetype
    - font-ttf-dejavu-sans-mono
  run:
    - openjdk >=11,<=12
    - xorg-libxtst
    - fontconfig
    - freetype
    - font-ttf-dejavu-sans-mono

test:
  commands:
    - "cytoscape.sh -v"

about:
  home: https://cytoscape.org
  license: LGPL
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Cytoscape: an open source platform for network analysis and visualization.'
  dev_url: https://github.com/cytoscape/cytoscape

extra:
  identifiers:
    - biotools:cytoscape
    - doi:10.1101/gr.1239303
