{% set version = "2.7.0" %}
{% set sha256 = "8415315c3fe5ac4c4e4ce4cb5dc9298e8a01399126d662373acc552b8aa6d70f" %}

package:
  name: hmftools-orange
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/orange-v{{ version }}/orange_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - zlib
    - openjdk >=8

test:
  commands:
    - 'orange 2>&1 | grep -q "ORANGE"'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/orange/README.md
  license:  "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: ORANGE summarizes the key outputs from all algorithms in the Hartwig suite.
