 {% set version = "1.2.2" %} 

package:
  name: sem
  version: '{{ version }}'

build:
  number: 0
  noarch: generic

source:
  sha256: a3667e8a138870ddd80405567ea7047af0a8319562db02e1e20935ec49aeb8f8
  url: https://github.com/YenLab/SEM/releases/download/v{{ version }}/sem-{{ version }}.tar.gz

requirements:
  run:
    - openjdk >=11.0.1,<12.0.0
    - python

test:
  commands:
    - sem --help

about:
  home: 'https://github.com/YenLab/SEM'
  license: "MIT"
  summary: "A nucleosome calling package for nucleosome subtype detection"

extra:
  recipe-maintainers:
    - yztxwd


