{% set name = "Medaka" %}
{% set version = "1.8.2" %}
{% set sha256 = "73e5669447c4b3a948da02d64cf6d416a64c303a6938d20607c17b3dd9f25241" %}
# Bot PRs - Always review requirements.txt for new release

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medaka-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patch

build:
  number: 0
  skip: True  # [py < 38]
  entry_points:
    - medaka = medaka.medaka:main
    - medaka_counts = medaka.medaka_counts:main
    - medaka_data_path = medaka.common:print_data_path
    - medaka_version_report = medaka:report_binaries

requirements:
  build:
    - {{ compiler('c') }}
    - coreutils
  host:
    - python
    - pip
    - cffi ==1.15.0
    - htslib
    - libcurl
    - openssl
    - bzip2
    - xz
    - zlib
  run:
    - python
    - cffi ==1.15.0
    - grpcio
    - h5py
    - intervaltree
    - tensorflow >=2.8.0,<2.9.dev0
    - numpy >=1.21.6
    - nomkl  # [osx]
    - mappy
    - ont-fast5-api
    - parasail-python
    - pyspoa >=0.0.3
    - pysam >=0.16.0.1
    - python-edlib
    - requests
    - samtools >=1.17
    - bcftools >=1.17
    - minimap2 >=2.26
    - htslib
    - libcurl
    - openssl

test:
  imports:
    - medaka
  commands:
    - medaka --help
    - medaka consensus --help
    - medaka_data_path
    - medaka_version_report

about:
  home: https://github.com/nanoporetech/medaka
  summary: Neural network sequence error correction.
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  dev_url: https://github.com/nanoporetech/medaka

extra:
  recipe-maintainers:
    - cjw85
  identifiers:
    - usegalaxy-eu:medaka_consensus
    - biotools:medaka
